name: demo3rdwheelhp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ##syncfusion_flutter_calendar: ^17.4.40-beta
  table_calendar: ^2.2.3
  shared_preferences: ^0.5.4+5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^1.4.4+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - images/cat.jpeg


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

